# Generated by Django 5.2 on 2025-10-16 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='name',
        ),
        migrations.AddField(
            model_name='busroute',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
