# Generated by Django 5.2 on 2025-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_system', '0002_remove_busroute_name_busroute_registered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('delay', 'Delay'), ('route', 'Route Change')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
