# Generated by Django 5.2 on 2025-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_system', '0003_rename_time_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='active',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('delay', 'Delay'), ('route', 'Route Change')], default='arrival', max_length=20),
        ),
    ]
