# Generated by Django 5.2 on 2025-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_system', '0004_remove_notification_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('delay', 'Delay'), ('route', 'Route Change')], max_length=20),
        ),
    ]
